// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteAllUsers.sql

package database

import (
	"context"
)

const deleteAllProducts = `-- name: DeleteAllProducts :exec
DELETE FROM users
`

func (q *Queries) DeleteAllProducts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllProducts)
	return err
}
