// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insertChip.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertChirps = `-- name: InsertChirps :one
INSERT INTO chirps (id, created_at, updated_at, body, user_id)
VALUES (
        gen_random_uuid(),
        now(),
        now(),
        $1,
        $2
       )
RETURNING id, created_at, updated_at, body, user_id
`

type InsertChirpsParams struct {
	Body   sql.NullString
	UserID uuid.NullUUID
}

func (q *Queries) InsertChirps(ctx context.Context, arg InsertChirpsParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, insertChirps, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
