// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: searchUserByEmail.sql

package database

import (
	"context"
	"database/sql"
)

const searchByEmail = `-- name: SearchByEmail :one
SELECT id, created_at, updated_at, email, hashed_password FROM users WHERE email = $1
`

func (q *Queries) SearchByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, searchByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
