// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usersFindAll.sql

package database

import (
	"context"
)

const usersFindAll = `-- name: UsersFindAll :many
SELECT id, created_at, updated_at, email, hashed_password FROM users
`

func (q *Queries) UsersFindAll(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, usersFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.HashedPassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
